Description bisection rule for carbon budget
SGIModel/MUSE_OS pull request #149
Opened 2023-08-05 22:12 UTC by sgiarols

# Description

*This PR adds comments on relevant sections of the code for carbon budget estimates based on the bisection rule.*

Fixes #143 

## Type of change

Please add a line in the relevant section of
[CHANGELOG.md](https://github.com/SGIModel/StarMuse/blob/development/CHANGELOG.md) to
document the change (include PR #) - note reverse order of PR #s.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [ ] All tests pass: `$ python -m pytest`
- [ ] The documentation builds and looks OK: `$ python -m sphinx -b html docs docs/build`

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2023-08-07 06:07 UTC, dalonsoa requested changes
I feel the docstrings could be a bit more informative, and possibly the code could be broken down into smaller bits. Otherwise, it looks good. 

I wonder why not using an[ out of the box bisection solver](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.bisect.html). Granted it could be tricky to setup, considering the complexity of the function to optimise, but we wouldn't need to worry about setting up the boundaries of the interval with each iteration.

2023-08-07 06:07 UTC, dalonsoa commented on src/muse/carbon_budget.py
> +    """Applies bisection algorithm to escalate carbon price and meet the budget.
I feel this needs a more detailed description of what this algorithm is about. Probably, also the other algorithm needs it, but given that we are clarifying this one, let's make it right.

2023-08-07 07:54 UTC, dalonsoa commented
Also, I don't think this PR should close #143 - that one is more broadly about how the Carbon Budget is described in the documentation, and not just about the bisection method, which is only part of what needs documenting.

2023-10-03 04:18 UTC, dalonsoa commented
HI @sgiarols , it would be good to take this out of the way at some point. Could you look into my comments and suggestions?

2023-10-17 09:12 UTC, sgiarols commented
I addressed the changes requested about improving documentation and the notes to the code

2023-10-17 09:23 UTC, dalonsoa approved these changes

2023-10-17 09:23 UTC, merged