Remove retro
SGIModel/MUSE_OS pull request #35
Opened 2022-05-12 13:29 UTC by dalonsoa

# Description

Adds a new version for the demand share that do not use retro agents - indeed, if they are present in the `Agents.csv` file, it will complain. Using this new demand share is set in the TOML file for each of the sectors. 

Fixes # NA

## Type of change

Please add a line in the relevant section of
[CHANGELOG.md](https://github.com/SGIModel/StarMuse/blob/development/CHANGELOG.md) to
document the change (include PR #) - note reverse order of PR #s.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [x] All tests pass: `$ python -m pytest`
- [x] The documentation builds and looks OK: `$ python setup.py build_sphinx`

## Further checks

- [x] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2022-05-16 09:10 UTC, sgiarols commented on src/muse/demand_share.py
> +    occurs from decommissioned assets.
years (instead of yearas)

2022-05-16 09:48 UTC, sgiarols commented on src/muse/demand_share.py
> +
If we only remove the "retrofit" agents from Agents.csv, we get this error:

 File "c:\users\sg2410\desktop\github\muse_os\src\muse\demand_share.py", line 463, in _inner_split
    total = sum(shares.values()).sum("asset")  # type: ignore
AttributeError: 'int' object has no attribute 'sum'

We may add this to the error lists with a message like:

"This error refers to an agent with no assets. To fix this error, check the capacity assigment to the agents. ONe possibility is that you have decided not to use "Retrofit" agents, as such you may have already removed them from the agent definition file and the file of technodata, the system TOML file should change the demand_share to "standard_demand" function in each subsector section for each of the selected sectors to model.

2022-05-16 22:05 UTC, sgiarols requested changes
- The assets are not initialised for the New agents. In the base year, the new agents should have the same assets as the retrofit.

- It may be useful to add a test on the __init__() function

https://github.com/SGIModel/MUSE_OS/blob/69a2bac60d6d19388094886ea47d993e975f0413/src/muse/agents/agent.py#L14

 to check that assets and all the attributes are properly initialised as for the retrofit agent (apart from the demand_share function) in the first year of the simulation.

- A new type of ineractions "new_to_new" should need to be recorded. This would take out the printout "subsector_name.interaction_name" and may probably guarantee that the assets should be inhertited and trasmitted properly form one period to the next after the investment is made.

2022-05-17 05:50 UTC, sgiarols commented on src/muse/demand_share.py
> +    occurs from decommissioned assets.
The steps to remove retro ahould be documented

2022-05-17 09:48 UTC, dalonsoa commented
Just to make sure I understand this right: when there is only `newcapa` agents in a given sector, the following line when creating the newcapa agent:

https://github.com/SGIModel/MUSE_OS/blob/69a2bac60d6d19388094886ea47d993e975f0413/src/muse/agents/factories.py#L112

Should be replaced by something similar to this one, taken from the retrofit creation, so the newcapa agents actually owns the assets:

https://github.com/SGIModel/MUSE_OS/blob/69a2bac60d6d19388094886ea47d993e975f0413/src/muse/agents/factories.py#L70

Is this correct?

2022-05-25 06:14 UTC, sgiarols commented
yes the interpretation makes sense.

2022-05-25 12:37 UTC, dalonsoa commented
So, how do you see this moving forward? Assuming all the code is ok - still to be seen after your review - For even the simplest model to run we will need to increase the cap in the mac capacity expansion in the technologies files, will surely affect other models.

2022-05-26 03:11 UTC, dalonsoa commented
I'm not sure what do you mean. The calculation does not pass the first year because of the constrains, as I described above, so I don' know how you got until 2050. Could you elaborate?

2022-05-26 06:11 UTC, sgiarols commented
I have increased the growth constraints in these runs, so the simulation goes to the end

2022-05-27 09:33 UTC, sgiarols commented
[default.zip](https://github.com/SGIModel/MUSE_OS/files/8785573/default.zip)
This is the case study I have been running.

2022-05-27 10:04 UTC, sgiarols commented
[Technodata.zip](https://github.com/SGIModel/MUSE_OS/files/8785797/Technodata.zip)

2022-05-27 10:10 UTC, dalonsoa commented
This model is not running for me using the same version of the PR. It complains of missing Retro agent. Did you change anything else in order to run it?

2022-05-27 10:32 UTC, sgiarols commented
nothing I can think of. can you paste the full error?

2022-05-27 12:18 UTC, dalonsoa commented
```
Exception has occurred: RetrofitAgentNotDefined
The retrofit agent has not been defined. This might be because it actually
has not been defined in the agents file or specified in the technodata file or it cannot
be found because there is a typo in its name in either the agents and or technodata
files. When a retrofit agent is defined in the agent file, the same name should be
reported as an additional column in the technodata, assigning the fraction of the
initial stock assigned to each retrofit agent. In presence of multiple retrofit agents,
a new column needs to be added per agent.

During handling of the above exception, another exception occurred:

  File "/Users/dalonsoa/Documents/Projects/MUSE_OS/src/muse/agents/factories.py", line 340, in _shared_capacity
    shares = technologies[share].sel(technology=capacity.technology)

During handling of the above exception, another exception occurred:

  File "/Users/dalonsoa/Documents/Projects/MUSE_OS/src/muse/agents/factories.py", line 342, in _shared_capacity
    raise RetrofitAgentNotDefined
  File "/Users/dalonsoa/Documents/Projects/MUSE_OS/src/muse/agents/factories.py", line 125, in create_newcapa_agent
    assets["capacity"] = _shared_capacity(
  File "/Users/dalonsoa/Documents/Projects/MUSE_OS/src/muse/agents/factories.py", line 170, in create_agent
    return method(**kwargs)  # type: ignore
  File "/Users/dalonsoa/Documents/Projects/MUSE_OS/src/muse/agents/factories.py", line 310, in agents_factory
    result.append(create_agent(**param, retrofit_present=retrofit_present))
  File "/Users/dalonsoa/Documents/Projects/MUSE_OS/src/muse/sectors/subsector.py", line 184, in factory
    agents = agents_factory(
  File "/Users/dalonsoa/Documents/Projects/MUSE_OS/src/muse/sectors/sector.py", line 54, in <listcomp>
    Subsector.factory(
  File "/Users/dalonsoa/Documents/Projects/MUSE_OS/src/muse/sectors/sector.py", line 53, in factory
    subsectors = [
  File "/Users/dalonsoa/Documents/Projects/MUSE_OS/src/muse/mca.py", line 74, in factory
    sectors.append(SECTORS_REGISTERED[kind](sector, settings))
  File "/Users/dalonsoa/Documents/Projects/MUSE_OS/src/muse/__main__.py", line 52, in muse_main
    MCA.factory(settings).run()
  File "/Users/dalonsoa/Documents/Projects/MUSE_OS/src/muse/__main__.py", line 55, in <module>
    muse_main()
```

2022-05-27 12:30 UTC, sgiarols commented
I see why this happened - because I had not yet incorporated the last changes. something in the last commits seem to get not recognised the absence of retrofit agents

2022-05-27 12:43 UTC, sgiarols commented on src/muse/agents/factories.py
>      **kwargs,
is it this one put to False afterwards?

2022-05-27 13:06 UTC, sgiarols commented on src/muse/agents/factories.py
This line forces to bring back the agent_share_2 line. It may need to be changed into smething more flexible, what if we have more than 1 agent?

2022-05-27 13:28 UTC, sgiarols commented on src/muse/agents/factories.py
To run the model, I had to change on line 123, "2" to "1". 
However, we may follow the same approach used for the standard_agent, here

`https://github.com/SGIModel/MUSE_OS/blob/9bf1957c28b0030a442f3bc24353f10943bc64d6/src/muse/agents/factories.py#L12`

2022-05-27 13:36 UTC, sgiarols commented
@dalonsoa 
now with the different initialisation, I do not have the capacity bounding, but the capacity does not meet the demand (without the algorithm failing) and the initialisation of the agent is too case specific as it requires agent_share_2 to be defined.

2022-05-27 13:38 UTC, dalonsoa commented
Ok, one thing at a time. You are actually right, but just let's make sure first we are on the same page.

I'm using as starting point to create a model that uses no retro agents the "default" example (this one: https://github.com/SGIModel/MUSE_OS/tree/develop/run/example/default). I changed two things there:
- Remove the retro agent row from "`Agents.csv`.
- Use `standard_demand` in the relevant places of the `settings.toml` file. 

Now, if I compare this with the model you have sent, I've found you also did this but, in addition there is also a difference in the `Technodata.csv` files. There you have only "Agent1", assigned to "New" for Power and Gas, but not for Residential where you had only "Agent2" assigned to "Retrofit". I think you probably just sent me the wrong Technodata file for residential.

So, if I fix the tehcnodata file file for Residential so it only has Agent1 with the thechnologies assigned to it and - as you point out - change `agent_share_2` by `agent_share_1`, then things run. 

Now, let's see if I can get rid of the hardcoding of `agent_share_1`.

2022-05-27 14:36 UTC, dalonsoa commented
@sgiarols , I think I've solved the problem. `share` was not enabled for `newcapa` agents - so even if you had several, they will not share the demand. I've enabled that by commenting the relevant liens in the readers and removed the hardcode of the agent share. 

Could you try now and see if (1) it runs and (2) the results make sense?

2022-05-27 15:53 UTC, sgiarols commented
I am running the defalt case and I get the bumps again
![image](https://user-images.githubusercontent.com/11628582/170734934-a139eba9-9f6a-48cd-b66b-ec7d777fe14a.png)

2022-05-31 15:36 UTC, dalonsoa commented
Ok, I think I've sorted out the issue. The problem was that `newcapa` agents have as default method for merging existing and new assets `new`, meaning that existing assets are discarded. That is not a problem normally because `newcapa` agents have no existing assets - they have been transferred to the `retrofit` agents via the interaction networks. However, in this case, it is a problem: we do want to keep existing assets. The solution was as simple as setting`merge_transform = "merge"` when creating the `newcapa` agents in the case when there is no `retro (in [this line](https://github.com/SGIModel/MUSE_OS/blob/bae1f7a1aa9415edb2d932118bc07ed2d474a4b6/src/muse/agents/factories.py#L128)). Fetch the last version of this PR to get the solution.

When that is done, the model runs all the way to the end, populating `MCACapacity.csv` and the other files with a sensible number of entries. Numerically it is a bit different from the case of having `retro` agents, but I think that is to be expected given that the constraints for the solver are different as long as the trends are the appropriate ones.  

I attach the `default` model - renamed `default_original` taken from `src/muse/data/example` - and exactly the same model without retrofit agents, renamed `default_no_retrofit`. I only had to increase the `MaxCapacityAddition` and `MaxCapacityGrowth` in the Residential technodata, and only by a factor of 2 and 2.5 respectively. For Power and Gas it was OK. The corresponding Results folders contain the actual results, so you can compare the trends without the need of running them.

[comparison.zip](https://github.com/SGIModel/MUSE_OS/files/8806617/comparison.zip)

2022-06-13 17:20 UTC, sgiarols commented
The changes make sense to me. 
Most of the time removing the retro does not change the results if it is a one-sector model or a multiple sector agent with the same objective. The attached mode, a three sector case with two agents, having two different objective functions, show two different results. Some situations may trigger just enough of a price change to induce a different technology section. In fact, the agents are investing using different capacities, which would affect the decisions.  So it seems reasonable that removing the retrofit agent results in a different model.
[modified.zip](https://github.com/SGIModel/MUSE_OS/files/8893197/modified.zip)

We need to check the failing tests during our call.

2022-06-13 18:14 UTC, sgiarols commented
Some fail ebcause the technodata in the tests does not contain "share". 
I interpret that the non investng aggregating agents do not use the share
![image](https://user-images.githubusercontent.com/11628582/173417590-4a06d510-a942-4251-a63d-fcae3aea02c1.png)

2022-06-13 18:14 UTC, sgiarols commented
Another one looks for agent_share 1
![image](https://user-images.githubusercontent.com/11628582/173418011-e6fd7d7d-3f1c-4a93-b0bf-6c3baa2ecb58.png)

2022-06-14 17:48 UTC, sgiarols commented
Part 1) I ran the trade case study.  The trade case runs with the folder here attached (only the residential needs to have the standard demand; power and gas are "dafault" agents which do not use retrofit). The trade default agents use a demand_share = "unmet_forecasted_demand", which does not account for the retrofit, they still need the agent share 
(you can see it from 
https://github.com/SGIModel/MUSE_OS/blob/develop/src/muse/data/example/trade/technodata/power/Technodata.csv
)
to distribute the capacity among the agents. However, in a pre-step the trade runs "nonInvestingAgent" which do not invest but updates metrics and do not need the share. THis is why the error is triggered

Part 2) Capacities.csv has, as I see, an error in the output. Apart from this reporting error, checking the outputs in the folders, they are pretty similar but in 2030 there is a 5 PJ difference in the residential sector. Here I can see an action about checking the capacity gap over time. I can try and do this.

Part 3) If we use standard_demand, the model would not complain about having the interaction section new_to_retro in the folder attached, I commented it, but maybe we should trigger an error?

Part 4) It seems we can rename the section in the toml, for example  I changed "new_to_retro" into "standard" in the toml section   [sectors.residential.subsectors.standard], and there is no complain about it. So I assume there is no consequence on the simulation.
[trade.zip](https://github.com/SGIModel/MUSE_OS/files/8902225/trade.zip)

2022-06-20 09:32 UTC, dalonsoa commented
Great! Thanks to tracking this down. I'll check 1) asap - possibly tomorrow. About 3 and 4, if there are no consequences, I'll leave it as it is for now and just change it when updating the documentation, as it is most likely a question of avoiding confusion for the users. I look forward to see what happens with 2. Please, let me know of the outcome.

2022-06-21 12:58 UTC, sgiarols commented
@dalonsoa 
I found that the default agent does not interpolate the "ExistingCapacity" appropriately. I therefore opened an issue about it. This is causing a dscrepancy for the residential sector. If I complete the decommissioning profile for each modelled year, then the residential sector converges to the same results. I opened an issue on this here
https://github.com/SGIModel/MUSE_OS/issues/46

I think that the current PR can be closed provided that the test causing the error for the 'non investing agent" is solved.

Then the documentation can be completed.

2022-06-23 07:42 UTC, dalonsoa commented
@sgiarols , this is finally passing. Please, review this and I'll start to work on the documentation (new issue open #47 ), as well as in the #33 .

2022-06-23 07:59 UTC, sgiarols approved these changes

2022-06-23 08:00 UTC, merged